name: Deploy to GitHub Pages

on:
  push:
    branches:
      - static.osmapp.org

permissions:
  id-token: write
  pages: write

jobs:
  hacky-static-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: gh-pages
      url: https://static.osmapp.org

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build hacky static export
        run: |
          export VERCEL_GIT_COMMIT_SHA="$(git rev-parse HEAD)"
          export VERCEL_GIT_COMMIT_MESSAGE="$(git log -1 --pretty=%B)"
          export NEXT_PUBLIC_FAKE_STATIC_EXPORT=true
          export NEXT_PUBLIC_FORCE_PROJECT=osmapp.org
          yarn build
          mkdir public/_next
          cp -r .next/static public/_next
          echo -e "User-agent: *\nDisallow: /" > public/robots.txt

          yarn start &
          sleep 5 # start usually takes 1 second

          curl --cookie "hideHomepage=yes" http://localhost:3000 > public/index.html
          curl --cookie "hideHomepage=yes" http://localhost:3000 > public/404.html
          for lang in de cs en es fr it pl am ja zh zh-CN zh-TW zh-HK; do
            mkdir public/$lang
            curl --cookie "hideHomepage=yes; lang=$lang" http://localhost:3000 > public/$lang/index.html
          done;

          # cache SSR version of some pages (eg. Prague)
          mkdir public/node
          mkdir public/node/1601837931
          curl --cookie "hideHomepage=yes" http://localhost:3000/node/1601837931 > public/node/1601837931/index.html

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
